apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: deploy
  labels:
    app: sendmail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sendmail
  template:
    metadata:
      labels:
        app: sendmail
    spec:
      containers:
        - name: my-app-sendmail
          image: mdianmareyah/sendemail-github:9
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-deployment
  namespace: deploy
  labels:
    app: sendmail
spec:
  type: LoadBalancer
  selector:
    app: sendmail
  ports:
    - port: 8080
